runtime: python27
api_version: 1
threadsafe: true
service: 'mail-service'

handlers:
- url: /.*
  script: main.app
- url: /_ah/mail/.+
  script: main.app

inbound_services:
- mail

libraries:
- name: ssl
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: 3.7.3